In [10]:
import numpy as np

In [11]:
a=np.array([1,2,3])
type(a)

numpy.ndarray

In [12]:
b=np.array([[10,2,8],[20,5,15]])
type(b)

numpy.ndarray

In [13]:
b.shape

(2, 3)

In [14]:
b

array([[10,  2,  8],
       [20,  5, 15]])

In [ ]:
n1=np.arange(27)      # Start at 0, end before 27
n1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
n2=np.arange(1,28)      # Start at 1, end before 28
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
n3=np.arange(1,28,9)       # Start at 1, end before 28, step by 9
n3

array([ 1, 10, 19])

In [ ]:
np.linspace(1,10,6)     # Start at 1, end at 10, 6 values

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])